CREATE TABLE Persons
(
  PersonId INT NOT NULL CONSTRAINT PK_Persons PRIMARY KEY
)

CREATE TABLE Orders
(
  OrderId int NOT NULL CONSTRAINT PK_Orders PRIMARY KEY,
  PersonId int FOREIGN KEY REFERENCES Persons (PersonId)
)
